import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:legacy_sync/core/extension/extension.dart';
import '../../../../../core/colors/colors.dart';
import '../../../../../core/components/comman_components/app_button.dart';
import '../../../../../core/images/images.dart';
import '../../../../my_podcast/data/podcast_model.dart';
import '../../bloc/play_podcast_cubit.dart';
import '../../bloc/play_podcast_state.dart';
import 'audio_play_controller.dart';


class TranscriptDescription extends StatefulWidget {
  final PodcastModel? podcast;

  const TranscriptDescription({super.key,this.podcast});

  @override
  State<TranscriptDescription> createState() => _TranscriptDescriptionState();
}

class _TranscriptDescriptionState extends State<TranscriptDescription> {
  @override
  void initState() {

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<PlayPodcastCubit, PlayPodcastState>(
      builder: (context, state) {
        final cubit = context.read<PlayPodcastCubit>();
        return Scaffold(
          backgroundColor: AppColors.bg_container_second,
          body: SafeArea(
            child: SingleChildScrollView(
              child: Column(
                children: [
                  _topHeader(state),
                  SizedBox(height: 0.5.height),
                  autoGeneratedTranscript(widget.podcast?.summary ?? ""),
                  SizedBox(height: 2.height),
                  autoGeneratedTranscript(widget.podcast?.summary ?? ""),
                  SizedBox(height: 2.height),
                  autoGeneratedTranscript(widget.podcast?.summary ?? ""),
                  // audioPlayBottomController()
                ],
              ),
            ),
          ),
         bottomNavigationBar: audioPlayBottomController(),
        );
      },
    );
  }

  Widget _topHeader(PlayPodcastState state) {
    Widget buildBackButton() {
      return AppButton(
        padding: const EdgeInsets.all(0),
        onPressed: () {
          Navigator.pop(context);
        },
        child: const Icon(
          Icons.arrow_back_ios,
          color: Colors.white,
          size: 20,
        ),
      );
    }

    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          buildBackButton(),
          Column(
            children: [
              const SizedBox(height: 2,),
              Text(
                widget.podcast?.title??'',
                style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  fontWeight: FontWeight.w700,
                  fontSize: 16,
                ),
              ),
              const SizedBox(height: 5,),
              Row(children: [
                Text(
                  "Me",
                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                    fontWeight: FontWeight.w600,
                    fontSize: 12,
                  ),
                ),
                Text(
                  ",",
                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                    fontWeight: FontWeight.w600,
                    fontSize: 12,
                  ),
                ),
                Text(
                  "Mom",
                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                    fontWeight: FontWeight.w600,
                    fontSize: 12,
                  ),
                ),
              ],),
            ],
          ),
      const SizedBox(width: 30,)
        ],
      ),
    );
  }


  Widget autoGeneratedTranscript(String transcriptText) {
    return Container(
      width: 363.width,
      padding: const EdgeInsets.all(10),
      margin: const EdgeInsets.symmetric(horizontal: 16),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const SizedBox(height: 2),
          Row(children: [
            Text(
              "04:96 ",
              style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                fontWeight: FontWeight.w400,
                fontSize: 10,
              ),
            ),
            Text(
              " • ",
              style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                fontWeight: FontWeight.w700,
                fontSize: 14,
              ),
            ),
            Text(
              " Mom",
              style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                fontWeight: FontWeight.w700,
                fontSize: 12,
              ),
            ),
          ],),
          const SizedBox(height: 12),
          Text(
            transcriptText,
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
              fontWeight: FontWeight.w700,
              fontSize: 16,
            ),
          ),
        ],
      ),
    );
  }

  Widget audioPlayBottomController() {

    return BlocBuilder<PlayPodcastCubit, PlayPodcastState>(builder: (context, state) {
      final cubit = context.read<PlayPodcastCubit>();
      return Container(
        height: 150,
        color: AppColors.primaryColorDart,
        padding: const EdgeInsets.only(left: 5,bottom: 10,right: 5),
        child: Stack(
        clipBehavior: Clip.none,
          children: [
            Positioned(top: -35,left: 0,right: 0, child: SvgPicture.asset(Images.sync)),
            AudioPlayController(state: state, cubit: cubit),
          ],
        ),
      );
    });
  }



}
